name: Send Hello to Telegram Bot

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot

      - name: Send Hello
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }} # Use GitHub secret
          TELEGRAM_CHAT_ID: 711856868
        run: |
          python -c "import asyncio; from telegram import Bot; async def main(): bot = Bot(token='${{ env.TELEGRAM_BOT_TOKEN }}'); await bot.send_message(chat_id='711856868', text='Hello'); await asyncio.sleep(1); asyncio.run(main())"
